application: nebree8
version: 10
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: static/app.html
  upload: static/app.html
- url: /
  static_dir: static
